---

czga_podman_runner_host: podman-runner
czga_clusters_namespace: clusters-sub
czga_kubeconfig_path: "{{ omit }}"
czga_policies_namespace: policies-sub
czga_oc_tool_path: "{{ oc_tool_path | default('/usr/local/bin/oc') }}"
czga_site_generator_image: registry.redhat.io/openshift4/ztp-site-generate-rhel8
czga_multicluster_image: registry.redhat.io/rhacm2/multicluster-operators-subscription-rhel9
